### ISSUE TITLE
New netcreate-itest settings cause crash in multiplex

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/nc-multiplex#1]
I updated all files to match the new directory structure and get this error when I run the multiplex and then attempt to open a db:

...nc-multiplex: 
...nc-multiplex: STARTED!
...nc-multiplex: 
[HPM] Proxy created: (pathname, req) => {
      // only match if there is a trailing '/'
      if (req.params.file) return true; // legit file
      if (req.params.graph && req.originalUrl.endsWith("/")) return true; // legit graph
      return false;
    }  -> http://localhost:3000
[HPM] Proxy created: /  -> http://localhost:3000
...nc-multiplex: running on port 80.
.......nc-start: 
.......nc-start: STARTING DB base
.......nc-start: 
.......nc-start: 1. Setting netcreate-config.js.
.......nc-start: 2. Starting server
ServerDB - LOADING DATABASE ./runtime/Testing.loki
APP_SERV -
APP_SERV - *** GO TO ONE OF THESE URLS in CHROME WEB BROWSER ***
APP_SERV - *** MAINAPP - http://localhost:3000
APP_SERV - *** CLIENTS - http://192.168.50.187:3000
APP_SERV -
SRV-NET  - UNISYS NETWORK initialized on port 2929
APP_SERV - brunch-server.js returning control to brunch
SRV-NET  - listening on port 2929
.......nc-start:  3. Server started on port 3000!
...nc-multiplex: Received message from spawned fork: nc-start.js: Completed!
...nc-multiplex: 
...nc-multiplex: base STARTED!
...nc-multiplex: 
ServerDB - DATABASE LOADED! m_max_nodeID '0', m_max_edgeID '0'
APP_SERV - ARCHITECTURE: arm64
APP_SERV - .. Expected i386, operation may be unstable
APP_SERV - .. For arm64 on mac, consider using Rosetta-compatible shell by running
APP_SERV - .. 'arch x86_64 /bin/zsh'
ServerDB - TEMPLATE LOADED ./runtime/Testing.template.toml
APP_SERV - GIT STATUS:
APP_SERV - .. You are running the "dev" branch
APP_SERV - NODE VERSION: v18.16.0 OK
...nc-multiplex: ================== Handling ERROR NO DATABASE!
...nc-multiplex: ================== Handling ERROR NO DATABASE!
...nc-multiplex: ================== Handling / ROOT!
...nc-multiplex: ================== Handling / MANAGE!
...nc-multiplex: ================== Handling / LOGIN!
...nc-multiplex: ================== Handling / AUTHORIZE!
...nc-multiplex: ================== Handling / MANAGE!
...nc-multiplex: --> not running yet, starting new Testing
.......nc-start: 
.......nc-start: STARTING DB Testing
.......nc-start: 
.......nc-start: 1. Setting netcreate-config.js.
.......nc-start: 2. Starting server
ServerDB - LOADING DATABASE ./runtime/Testing.loki
APP_SERV -
APP_SERV - *** GO TO ONE OF THESE URLS in CHROME WEB BROWSER ***
APP_SERV - *** MAINAPP - http://localhost:3001
APP_SERV - *** CLIENTS - http://192.168.50.187:3001
APP_SERV -
SRV-NET  - UNISYS NETWORK initialized on port 2929
APP_SERV - brunch-server.js returning control to brunch
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:2929
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on WebSocketServer instance at:
    at WebSocketServer._onServerError (/Users/jdanish/gitcode/nc-multiplex/netcreate-itest/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (node:events:513:28)
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 2929
}

Node.js v18.16.0

**Comment by benloh** [comment]
# Debugging Log
* Current `nc-multiplex` is on node v10.22.0.  But `netcreate-itest` is on v18.16.0.
  * Try running `nc-multiplex` on 18.16.1 (for `nc-multiplex` and `netcreate-itest`)
 
# Fix
@jdanish I think the issue is node versions.
Current `nc-multiplex` is on node v10.22.0.  But `netcreate-itest` is on v18.16.0.  
You need to update node to version 18.16.0.
And use `npm run package` on `netcreate-itest` instead of `npm run classroom`

I'll update the readme.
