### ISSUE TITLE
OutOfMemory() method 

### ISSUE THREAD

**Issue by benloh** [netcreateorg/nc-multiplex#10]
After merging #7,

In spite of having plenty of memory (e.g. here there's 582MB)...

![screenshot_1704](https://github.com/user-attachments/assets/9b564a55-5f2d-45b5-95cb-d49732a42cc4)

Opening a saved graph always results in an out of memory error:

![screenshot_1703](https://github.com/user-attachments/assets/495f2ed5-42ea-41eb-bac7-9c426dcb315e)

## To Replicate
1. Go to http://24.144.94.149/manage (inquirium server)
2. Check memory > 256MB free
3. Click "demo" or "monaug19" to open saved graph
4. `Ran out of Memory. Can't start the graph.` error.

---

## Investigating

Maybe I'm reading this wrong, but doesn't `OutOfMemory()` always return true?
```
/// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/** Used to check if we have enough memory to start a new node process
 *  This is used to prevent node from starting too many processes.
 */
function OutOfMemory() {
  const bytesToMB = 1024 * 1024;
  let free = os.freemem() / bytesToMB; // mb
  const warnMem = SYSMEM_MIN;
  const critMem = SYSMEM_MIN / 4;
  const low = free < critMem;
  const warn = free < warnMem;
  if (low) return `**CRITICAL** (< crit fail buffer ${critMem}MB)`;
  if (warn) return `**WARNING** (< mem buffer ${warnMem}MB`;
  return `OK (>${SYSMEM_MIN}MB free)`;
}
```
So while `RenderMemoryReport()` is correctly using `OutOfMemory()` to retrieve a message,
`m_RouterLogic():833` is relying on  `OutOfMemory()` to return true or false.

**Comment by dsriseah** [comment]
I'll add a specific memory check and separate this from MemoryReport.

**Comment by benloh** [comment]
Confirmed fixed.
