### ISSUE TITLE
Tokens generated by vfoi-staging 159.203.177.172 are not working

### ISSUE THREAD

**Issue by benloh** [netcreateorg/nc-multiplex#9]
Tokens generated by **vfoi-staging 159.203.177.172** ...
* via `/manage` on nc-multiplex do **NOT** work
* via `ncMakeTokens` in the web console **do** work

Joshua reports that **vfoi-itest 198.211.109.198** has the same problem.

**Comment by benloh** [comment]
## via `/manage`
```
TOKEN LIST for class 'cook' project 'now' dataset 'amanRecipes'

group 1	COOK-NOW-2D4
group 2	COOK-NOW-2QL
group 3	COOK-NOW-2J6
```

## via webconsole
```
> ncMakeTokens('cook','now','amanRecipes',3)
TOKEN LIST for class 'cook' project 'now'

group 1	COOK-NOW-829
group 2	COOK-NOW-8GM
group 3	COOK-NOW-J3V
```

NOTE that running `ncMakeTokens` without the `dataset` name does result in the correct token:
```
> ncMakeTokens('cook','now','',3)
[Log]  (netc-app.js, line 35035)
TOKEN LIST for class 'cook' project 'now'

group 1	COOK-NOW-2D4
group 2	COOK-NOW-2QL
group 3	COOK-NOW-2J6
```

and `ncMakeSharedTokens` is not defined.


## 159
`nc-multiplex` -> `dev-sri/timestamps` 
* SHA `ce34f8b`

`netcreate-itest` -> `dev`
* SHA `babb3a3`

**Comment by dsriseah** [comment]
I'd check to see if the maketokens in nc-multiplex is up-to-date if it's not somehow digging into the netcreate-itest subrepo.

**Comment by benloh** [comment]
# LOG

- [X] Both `nc-multiplex` and `netcreate-itest` are on the correct most recent `dev` branches
- [X] Running `ncMakeTokens` without the dataset ncMakeTokens('cook','now','',3) does work.
- [X] ncMakeSharedTokens is NOT available?
- [X] `npm run package` should run `". ./@build-ursys.sh && brunch build -e package",` -- `". ./@build-ursys.sh && brunch w -s",`
- [X] `nc-logic.js` should include `ncMakeSharedToken` script => It does!
- [X] Replicate on 24.144.94.149
   - [X] Checkout `dev` and simply `npm run package` -- `ncMakeSharedTokens` should be available
   - [X] Checkout OLD branch without `ncMakeSharedTokens`
   - [X] Does webconsole still have ncMakeSharedTokens?  YES!  It should because while the code has changed, the built scripts haven't.
   - [X] `npm run package` -- `ncMakeSharedTokesn` should now be gone.
   - [X] Now we've replicated the current state of 159
   - [X] Now checkout `dev` again without running `npm run package` -- `ncMakeSharedTokens` should still be gone.
   - [X] `npm run package` -- `ncMakeSharedTokesn` should now should work?  NO! It doesn't!
   - [X] Does stopping and restarting the graph fix it? => YES.
- [X] Try 159
   - [x] `npm run package` fails => low mem.  Close graphs.
   - [X] Try stopping and restarting => That fixes it.

CONCLUSION: Two points:
1. Most likely culprit was that `npm run package` was not run?
2. The graph needs to be stopped and restarted for the new code to run.

**Comment by benloh** [comment]
Resolved with run package update.
